### ISSUE TITLE
Minimum CF version?

### ISSUE THREAD

**Issue by arthurblake** [mjclemente/sendgrid.cfc#14]
What version of CF was this targeted for? I am stuck on an older version for various reasons (Railo 3). I started to test the library and quickly ran into newer CF constructs (like Closures) that I had to rewrite (it is still not working yet and not sure if it's worth going down this path.) Would be nice if the README.md addressed the minimal supported CF versions or at least suggested CF version? Thank you.

**Comment by mjclemente** [comment]
Hi! Sorry about the issues you're having with the project.

My goal would be that the project would work on the currently supported CF Engines. So, for ACF right now that would be ColdFusion 2018 and for Lucee, I think it would be at a minimum Lucee 5 - probably more like 5.3, because I think that's as far back as their security fixes will go. Which I guess leaves Railo out in the cold - and I'm sorry about that. I wouldn't even have a solid way to test for Railo 3 support.

I appreciate your suggestion about adding that info to the README - I'll do that.

Thank you, and I'm sorry this isn't of more help to you. If there's anything else I can do to give you a hand, let me know.

**Comment by mjclemente** [comment]
closed with [#8ecac30](https://github.com/mjclemente/sendgrid.cfc/commit/8ecac3070f99874a6c44c3fba6a4a528f546e11f)
